pool:
  vmImage: ubuntu-latest

variables:
- name: ACR
  value: ACR_URL
- name: AZURE_STORAGE_CONNECTION_STRING 
  value: AZURE_STORAGE_CONNECTION_STRING
- name: ACR_USER
  value: ACR_USER
- name: ACR_PASSWORD
  value: ACR_PASSWORD
- name: PROJECT
  value: prefect


stages:
- stage: deployment
  jobs:
  - job: detect
    steps:
       #detect any changes in the flows directory
       - template: templates/detect-changes.yml
         parameters:
            include: flows/
       
  - job: register
    dependsOn: detect
    pool: private-agent
    variables:
       RESULT: $[dependencies.detect.outputs['detect.RESULT']]
       IMAGE_URL: "$(ACR)/$(PROJECT):latest"
    steps:
       #register the flows that changed
       - template: templates/register-flows.yml
         parameters:
            project: $(PROJECT)
            flows: $RESULT
  
  - job: build
    dependsOn: register
    steps:
       #build a docker image and push it to ACR
       - template: templates/docker-build.yml
         parameters:
              image: "$(ACR)/$(PROJECT)"
              tag: latest
                    
       - template: templates/docker-login.yml
         parameters:
              repo: $(ACR)
              user: $(ACR_USER)
              password: $(ACR_PASSWORD)

       - template: templates/docker-push.yml
         parameters:
             image: "$(ACR)/$(PROJECT)"
             tag: latest

trigger:
  branches:
     include:
        - '*'
  paths:
     include:
       - 'flows/'
       - 'tasks/'
       - 'config/'
     exclude:
       - '*'
       - '*__init__.py*'
